### ISSUE TITLE
Outdated Persona Bond Forge patch

### ISSUE THREAD

**Issue by thailyn** [emipa606/HeavyMeleeWeapons#2]
I've always found the Persona Bond Forge mod and its patches and patch mods a bit confusing, as there are so many versions (similar to the research tree mods), but I think I have it figured out.

This mod (HeavyMeleeWeapons) references in its original description the old [Persona Bond Forge](https://steamcommunity.com/sharedfiles/filedetails/?id=2178003816) mod and has a patch for using it, which references a `BondingCore` ThingDef that the Persona Bond Forge mod defines.

However, this old Persona Bond Forge mod has not been updated since RimWorld 1.3. I believe it is safe to say the "new" [Persona Bond Forge](https://steamcommunity.com/sharedfiles/filedetails/?id=2881724503) mod is the defacto replacement, as it supports RimWorld 1.4 and has been relatively recently updated. I've had it loaded in my mod lists for a while, but never actually did much with it so far.

This new mod has a different package id ("StatistNo1.personabond", versus the old "xedos.personabond"), but, unfortunately, it has the same mod name, so any patches which were intended to find the old version (via PatchOperationFindMod) also find the new version.

This new mod, however, does not define a `BondingCore` ThingDef. I believe it instead defines a `PersonaBondForge_ThingDef_BondingCore` (the ThingDef still has the label "bonding core" and the descriptions are similar). Old patches that reference `BondingCore` lead to errors in the log:

```
Could not resolve cross-reference to Verse.ThingDef named BondingCore (wanter=thingDefs)

Could not resolve cross-reference to Verse.ThingDef named BondingBench (wanter=recipeUsers) 
```

Similarly, there is now a `PersonaBondForge_ThingDef_BondingBench` instead of a `BondingBench`.

Both of these ThingDefs appear to be referenced in RecipeDefs that are patched in to support creating the persona weapons.

Thus, I think the solution would be to reference these new ThingDefs, as those are defined in the updated Persona Bond Forge mod. I guess in theory you could add additional checks to make sure the new ThingDefs are defined, but that would require loading this mod after Persona Bond Forge, and the Persona Bond Forge's description says to load it *after* "all mods that add persona weapons", which smells dangerously close to a circular dependency if more care than should be needed for mod load order is not taken.

---

Side note: the errors in the log do not give any hint as to what mod tried and failed to resolve the cross-reference or how many attempts the mod made, so I had to manually find which mods were referencing `BondingCore`/etc. This mod was just the first I looked in to. I have a whole bunch of copies of these errors in my log file, so I might turn around and file similar bugs for other mods sooner or later. It's a low-severity error, though, so it might not be right away.

**Comment by emipa606** [comment]
Should be fixed now in b7217d7
Just added some MayRequire-tags in the patch

For example:
https://github.com/emipa606/HeavyMeleeWeapons/blob/b7217d7214b50275049a71dc910cf31b36411d3d/1.4/Patches/PersonaBondForge.xml#L34-L35

Thanks for the detailed report!
